CREATE DATABASE IF NOT EXISTS devices;
CREATE DATABASE IF NOT EXISTS devices_account;
CREATE USER IF NOT EXISTS 'devices'@'%' IDENTIFIED BY 'db_password';
GRANT ALL PRIVILEGES ON devices.* TO 'devices'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON devices_account.* TO 'devices'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;